[package]
name = "weatherlogger"
version = "0.1.0"
authors = ["Fredrik Hagen Fasteraune <freddahf@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11" }
serde_json = "1.0.60"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
csv = "1.1"
sqlite = "0.24.0"
plotters = "^0.3.1"
rayon = "1.5.1"
futures = "0.3.17"
